"""empty message

Revision ID: 45d63624e49e
Revises: 6e39847318ca
Create Date: 2018-02-13 19:06:44.741280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d63624e49e'
down_revision = 'f3542f6a46f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mobile_prompt_responses', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mobile_prompt_responses', sa.Column('prompt_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mobile_prompt_responses', 'prompt_num')
    op.drop_column('mobile_prompt_responses', 'edited_at')
    # ### end Alembic commands ###
